import { Sparkles } from "lucide-react";
import { useCrewBriefing } from "../hooks/useCrewBriefing";

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
  });
}

/** Minimal markdown → JSX: bold (**text**) and numbered lists. */
function renderBriefing(text: string) {
  return text.split("\n").map((line, i) => {
    if (!line.trim()) return <br key={i} />;

    // Convert **bold** markers to <strong>
    const parts = line.split(/(\*\*[^*]+\*\*)/g).map((seg, j) => {
      if (seg.startsWith("**") && seg.endsWith("**")) {
        return (
          <strong key={j} className="text-slate-100 font-bold">
            {seg.slice(2, -2)}
          </strong>
        );
      }
      return seg;
    });

    return (
      <p key={i} className="text-xs text-slate-300 leading-relaxed">
        {parts}
      </p>
    );
  });
}

export function CrewBriefingPanel() {
  const { briefing, loading } = useCrewBriefing();

  if (loading || !briefing) return null;

  return (
    <div className="glass rounded-2xl border border-violet-500/20 bg-violet-500/[0.04] p-4">
      <div className="flex items-center justify-between mb-3">
        <p className="text-[0.62rem] font-bold uppercase tracking-wider text-violet-300 flex items-center gap-1.5">
          <Sparkles size={11} />
          Weekly crew briefing
        </p>
        <span className="text-[0.55rem] text-slate-600">
          {formatDate(briefing.generatedAt)}
        </span>
      </div>
      <div className="space-y-1">{renderBriefing(briefing.briefing)}</div>
      {briefing.daysUntilTrip > 0 && (
        <p className="text-[0.55rem] text-violet-400/60 mt-3">
          {briefing.daysUntilTrip}d until wheels up · generated by GLM 5.1
        </p>
      )}
    </div>
  );
}
